---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dot-os
description: Dot OS

base-image: quay.io/fedora/fedora-silverblue
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    optfix:
      - google
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tour
      - malcontent-control
    install:
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

  - type: default-flatpaks
    user: {}

  - type: signing
