---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dot-os
description: Dot OS

base-image: quay.io/fedora/fedora-silverblue
image-version: 41

modules:
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    user: {}

  - type: signing
